[package]
name = "rusty"
version = "0.1.0"
authors = ["William Santasiero <william.santasiero@aceindustries.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.10.1"
env_logger = "0.5.11"

[dependencies.url]
version = "2.1.0"

