apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rusty
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: rusty
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rusty
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: rusty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rusty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rusty
  template:
    metadata:
      labels:
        app: rusty
    spec:
      containers:
        - name: rusty
          image: docker.io/wsantas/rusty
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rust-web-demo-postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: rust-web-demo-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-web-demo-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-web-demo-postgres
  template:
    metadata:
      labels:
        app: rust-web-demo-postgres
    spec:
      containers:
        - name: rust-web-demo-postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: rusty
            - name: POSTGRES_USER
              value: diesel
            - name: POSTGRES_PASSWORD
              value: changeme
